---
title: "iso-syn"
author: "Katie Bennett"
date: "9/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## First, install and load libraries
```{r}
#Packages to install (you only need to do this once)
#For data analysis:
install.packages("tidyverse") #includes dplyr, ggplot2
install.packages("maps")
install.packages("ggmap")
install.packages("na.tools")
install.packages("agricolae")
install.packages("naniar")
install.packages("svglite") #to export graphs as .svg files

#For loading the ISRaD package below:
install.packages("devtools")
install.packages("rcrossref")

#Load these packages (you need to do this every time you restart R)
library(tidyverse)
library(maps)
library(ggmap)
library(devtools)
library(rcrossref)
library(na.tools)
library(agricolae)
library(naniar)
library(svglite) #to export graphs as .svg files

#Install package 'ISRaD' from our branch of the ISRaD github repository: this could take a few minutes, don't panic
devtools::install_github("International-Soil-Radiocarbon-Database/ISRaD/Rpkg", ref="pcn-syn", force = T) #change ref= to "master" to use public version of the package
library(ISRaD) # load the package
```

## Compile templates and create "flat" dataframes for layers of interest
```{r}
#compiling templates, compile function also runs QAQC on all included templates
compiled<-compile(dataset_directory = "C:/Users/katie/Documents/R/pcn-iso-syn/data", write_report = T, write_out = T, return="list")

#to run QAQC on a single template: 
# QAQC("C:/Users/katie/Documents/R/pcn-iso-syn/data/Quay_1988.xlsx") #change file path

#run ISRaDExtra functions, can run all together using ISRaD.extra.R or can run individually. Best to run them together bc some need to be run in order/rely on eachother
ISRaD.extra(compiled)  #need to specify a geospatial database
#ISRaD.extra.Cstocks(compiled)
#ISRaD.extra.delta_delta(compiled)
#ISRaD.extra.fill_14c(compiled)
#ISRaD.extra.fill_coords(compiled)
#ISRaD.extra.fill_dates(compiled)
#ISRaD.extra.fill_fm(compiled)

#use built-in flatten function in ISRaD package to create "flat" dataframes
flux_data <- ISRaD.flatten(compiled, 'flux') #enter name of dataset and table that you want data for
inter_data <- ISRaD.flatten(compiled, 'interstitial')

```

further data cleaning and filtering dataframes for our variables of interest
```{r}
## First, flux data
#replacing NAs for permafrost and thermokarst with absent/no
flux_data$pro_permafrost <- na.replace(flux_data$pro_permafrost, "absent")
flux_data$pro_thermokarst <- na.replace(flux_data$pro_thermokarst, "no")
flux_data$pro_permafrost <- recode(flux_data$pro_permafrost, "yes" = "present") 

#filtering CH4 flux data
flux_CH4 <- flux_data %>%
  select(entry_name, site_lat, site_long, site_datum, flx_analyte, flx_13c, flx_2h, pro_thaw_depth, pro_depth_water, pro_land_cover, pro_water_body, pro_permafrost, pro_thermokarst, pro_wetland_type, pro_lake_depth, pro_lake_SA, pro_lake_sediment) %>% #filters down to only the named columns
  filter(flx_analyte == "CH4") %>%  #filters for CH4 data.
  replace_with_na(replace = list(pro_land_cover = "wetland")) %>% #replaces wetland landcover type w NA for simplicity (not totally necessary)
  unite("cover_type", c(pro_land_cover, pro_water_body, pro_wetland_type), remove = FALSE) #creates 1 new column w land_cover, water_body, and wetland_type

##recoding cover type classes
 flux_CH4$cover_type <- as.factor(flux_CH4$cover_type)
 flux_CH4$cover_type <- recode(flux_CH4$cover_type, "NA_Lake_NA"  = "lake") 
 flux_CH4$cover_type <- recode(flux_CH4$cover_type, "NA_NA_bogs"  = "bogs")
 flux_CH4$cover_type <- recode(flux_CH4$cover_type, "NA_NA_fens"  = "fens")
 flux_CH4$cover_type <- recode(flux_CH4$cover_type, "NA_NA_wetland_general"  = "general wetland")
 flux_CH4$cover_type <- recode(flux_CH4$cover_type, "tundra_NA_NA"  = "tundra")
 
 
 
#filtering CO2 flux data
flux_CO2 <- flux_data %>%
  select(entry_name, site_lat, site_long, site_datum, flx_analyte, flx_13c, pro_thaw_depth, pro_depth_water, pro_land_cover, pro_water_body, pro_permafrost, pro_thermokarst, pro_wetland_type, pro_lake_depth, pro_lake_SA, pro_lake_sediment) %>% #filters down to only the named columns
  filter(flx_analyte == "CO2") %>% #filters for CO2 data.
  replace_with_na(replace = list(pro_land_cover = "wetland")) %>% #replaces wetland landcover type w NA for simplicity (not totally necessary)
  unite("cover_type", c(pro_land_cover, pro_water_body, pro_wetland_type), remove = FALSE) #creates 1 new column w land_cover, water_body, and wetland_type

##recoding cover type classes
 flux_CO2$cover_type <- as.factor(flux_CO2$cover_type)
 flux_CO2$cover_type <- recode(flux_CO2$cover_type, "NA_Lake_NA"  = "lake") 
 flux_CO2$cover_type <- recode(flux_CO2$cover_type, "NA_NA_bogs"  = "bogs")
 flux_CO2$cover_type <- recode(flux_CO2$cover_type, "NA_NA_wetland_general"  = "general wetland")
 flux_CO2$cover_type <- recode(flux_CO2$cover_type, "tundra_NA_NA"  = "tundra")
```


Plot flux data
```{r}
#no 13c-co2 data, 1 2h point 9/14/20
#making plot of fluxex by cover type for 13c-CH4

p1 <- ggplot()+
  geom_boxplot(aes(x=flux_CH4$cover_type, y = flux_CH4$flx_13c, fill = flux_CH4$cover_type))+
  labs(x = "", y = expression(paste("Flux "*delta^{13}, "C-CH"[4]*" (\u2030)")), fill = "Cover Type") +
    ylim(-80,-50)+
    annotate("text", x = 1, y = -80, label = "4 studies") + #this number needs to be updated as studies are added
   annotate("text", x = 1, y = -50, label = "n = 1") +
  annotate("text", x = 2, y = -50, label = "n = 1") +
  annotate("text", x = 3, y = -50, label = "n = 10") +
  annotate("text", x = 4, y = -50, label = "n = 3") +
  annotate("text", x = 5, y = -50, label = "n = 1") +
  theme_classic()
p1
  #theme(axis.text.x = element_blank()) #removes x axis labels

#flx_ch4 <- ggplot(data = flux_CH4, aes(x = cover_type, y = flx_13c, size = 5))+
 # geom_point(aes(colour = cover_type))+ #says to color by cover_type
  # labs(x = "", y = expression(paste("Flux "*delta^{13}, "C-CH"[4]*" (\u2030)"))) + #axis labels
   # ylim(-80,-45)+ #sets y-axis limits
    #scale_colour_discrete("Cover Type")+ #chnages legend title
    #guides(size = FALSE)+ #removes size from legend
    #annotate("text", x = 1, y = -80, label = "2 studies") + #this number needs to be updated as studies are added
#  theme_classic()+
 # theme(axis.text.x = element_blank())
  #flx_ch4

#ggsave(file="ch4flx.jpg", flx_ch4)
```

data cleaning and filtering
```{r}
## Now interstitial data
#replacing NAs for permafrost and thermokarst with absent/no
inter_data$pro_permafrost <- na.replace(inter_data$pro_permafrost, "absent")
inter_data$pro_thermokarst <- na.replace(inter_data$pro_thermokarst, "no")
inter_data$pro_permafrost <- recode(inter_data$pro_permafrost, "yes" = "present") 

#filtering CH4 ist data
inter_CH4 <- inter_data %>%
  select(entry_name, site_lat, site_long, site_datum, ist_analyte, ist_13c, ist_2h, pro_thaw_depth, pro_depth_water, pro_land_cover, pro_water_body, pro_permafrost, pro_thermokarst, pro_wetland_type, pro_lake_depth, pro_lake_SA, pro_lake_sediment) %>% #filters down to only the named columns
  filter(ist_analyte == "CH4") %>%  #filters for CH4 data.
  replace_with_na(replace = list(pro_land_cover = "wetland")) %>% #replaces wetland landcover type w NA for simplicity (not totally necessary)
  unite("cover_type", c(pro_land_cover, pro_water_body, pro_wetland_type), remove = FALSE) #creates 1 new column w land_cover, water_body, and wetland_type

##recoding cover type classes
 inter_CH4$cover_type <- as.factor(inter_CH4$cover_type)
 inter_CH4$cover_type <- recode(inter_CH4$cover_type, "tundra_pond_NA"  = "pond") 
 

#filtering CO2 ist data
inter_CO2 <- inter_data %>%
  select(entry_name, site_lat, site_long, site_datum, ist_analyte, ist_13c, pro_thaw_depth, pro_depth_water, pro_land_cover, pro_water_body, pro_permafrost, pro_thermokarst, pro_wetland_type, pro_lake_depth, pro_lake_SA, pro_lake_sediment) %>% #filters down to only the named columns
  filter(ist_analyte == "CO2") %>%  #filters for CH4 data.
  replace_with_na(replace = list(pro_land_cover = "wetland")) %>% #replaces wetland landcover type w NA for simplicity (not totally necessary)
  unite("cover_type", c(pro_land_cover, pro_water_body, pro_wetland_type), remove = FALSE) #creates 1 new column w land_cover, water_body, and wetland_type

#recoding cover type classes
 inter_CO2$cover_type <- as.factor(inter_CO2$cover_type)
 inter_CO2$cover_type <- recode(inter_CO2$cover_type, "tundra_pond_NA"  = "pond") 
 
 
#plot 13c-ch4, co2 ist data, no 2h data 9/14/2020
 
 p2 <- ggplot()+
  geom_boxplot(aes(x=inter_CH4$cover_type, y = inter_CH4$ist_13c, fill = inter_CH4$cover_type))+
  labs(x = "", y = expression(paste("Interstitial "*delta^{13}, "C-CH"[4]*" (\u2030)")), fill = "Cover Type") +
    ylim(-80,-50)+
    annotate("text", x = 1, y = -80, label = "1 study") + #this number needs to be updated as studies are added
   annotate("text", x = 1, y = -50, label = "n = 8") +
  theme_classic()
p2


 p3 <- ggplot()+
  geom_boxplot(aes(x=inter_CO2$cover_type, y = inter_CO2$ist_13c, fill = inter_CO2$cover_type))+
  labs(x = "", y = expression(paste("Interstitial "*delta^{13}, "C-CO"[2]*" (\u2030)")), fill = "Cover Type") +
   ylim(-30,-10)+
    annotate("text", x = 1, y = -30, label = "1 study") + #this number needs to be updated as studies are added
   annotate("text", x = 1, y = -10, label = "n = 8") +
  theme_classic()
p3
```

## Map the data
```{r}
#First, setup basemap
world_map <- map_data("world")

#Creat a base plot with gpplot2
p <- ggplot() + coord_fixed() +
  xlab("") + ylab("")

#Add map to base plot
#Pick color words here: http://sape.inf.usi.ch/quick-reference/ggplot2/colour
base_world_messy <- p + geom_polygon(data=world_map, aes(x=long, y=lat, group=group), 
                                     colour="cadetblue4", fill="cadetblue4")

cleanup <- theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                 panel.background = element_rect(fill = 'white', colour = 'white'), 
                 axis.line = element_line(colour = "white"), legend.position="bottom",
                 axis.ticks=element_blank(), axis.text.x=element_blank(),
                 axis.text.y=element_blank())

base_world <- base_world_messy + cleanup
base_world #Plots map to screen
#base_world_messy
```

Plot locations of profiles on the map
```{r}
#Filter only data with 13C:
#commented out lines above filtering for >60N so all 13C data in ISRaD is displayed
 flux_CH4_13c <- flux_CH4 %>%
  dplyr::filter(is.na(flx_13c) != TRUE)
flux_CO2_13c <- flux_CO2 %>%
  dplyr::filter(is.na(flx_13c) != TRUE)
inter_CH4_13c <- inter_CH4 %>%
  dplyr::filter(is.na(ist_13c) != TRUE)
inter_CO2_13c <- inter_CO2 %>%
  dplyr::filter(is.na(ist_13c) != TRUE)

#plot flux 13C-CH4 data and flux 13c_CO2
map_all <- base_world_messy +
  geom_point(data=flux_CO2_13c, #lyr_all, #put incubation data here to plot points
             aes(x=site_long, y=site_lat), colour="black", 
             shape = 21, size=4, alpha=I(0.7), fill = "red")+
  geom_point(data=flux_CH4_13c, #lyr_all, #put incubation data here to plot points
           aes(x=site_long, y=site_lat), colour="black", 
           shape = 21, size=4, alpha=I(0.7), fill = "goldenrod1")+
  geom_point(data=inter_CO2_13c, #lyr_all, #put incubation data here to plot points
             aes(x=site_long, y=site_lat), colour="black", 
             shape = 21, size=4, alpha=I(0.7), fill = "green")+
  #geom_point(data=inter_CH4_13c, #lyr_all, #put incubation data here to plot points
           #aes(x=site_long, y=site_lat), colour="black", 
           #shape = 21, size=4, alpha=I(0.7), fill = "blue")+
theme(legend.position = "bottom")+
  ggtitle("13C Flux and Interstitial Data")
  ggsave("map_13Cfluxdata_clean.png", plot = map_all)

map_all # Plots map to screen
```

